### ISSUE TITLE
Python and Javascript

### ISSUE THREAD

**Issue by ngoue** [doconix/transcrypt_module#1]
Looks like you're transpiling Python to Javascript.  Have you tried just writing Javascript?

**Comment by tgroshon** [comment]
👍 
The VanillaJS system has proven to be the most efficient way of writing and running JavaScript: http://vanilla-js.com/

**Comment by shlomif** [comment]
On Fri, 06 Apr 2018 14:01:33 +0000 (UTC)
Jordan <notifications@github.com> wrote:

> Looks like your transpiling Python to Javascript.  Have you tried just
> writing Javascript?
> 

Please do not troll - see https://en.wikipedia.org/wiki/Internet_troll .

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Interview with Ben Collins-Sussman - http://shlom.in/sussman

Knuth is not God! Typing “God” into Google and pressing “I’m Feeling Lucky”
will not lead you to his homepage.
    — http://www.shlomifish.org/humour/bits/facts/Knuth/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
